---
- name: Install etcd
  action: "{{ ansible_pkg_mgr }}"
  args:
        name: etcd
        state: latest
  notify:
    - restart etcd
  when: not is_atomic

- name: Write etcd config file
  template: src=etcd.conf.j2 dest=/etc/etcd/etcd.conf
  notify:
    - restart etcd

- name: Write etcd systemd unit file for Debian
  copy: src=etcd.service dest=/etc/systemd/system
  notify:
    - reload systemd
    - restart etcd
  when: ansible_distribution == "Debian"

- name: Enable etcd
  service: name=etcd enabled=yes

- name: Start etcd
  service: name=etcd state=started
  register: etcd_started

- name: Update {{ etcd_script_dir }} if this is atomic
  set_fact:
     etcd_script_dir: "/usr/local/libexec/etcd"
  when: is_atomic

- name: Create etcd script directory
  file: path={{ etcd_script_dir }} state=directory

- name: overwrite setup-etcd.sh from local copy
  copy: src=setup-etcd.sh dest={{ etcd_script_dir }} mode=0500

- include: firewalld.yml
  when: has_firewalld

- include: iptables.yml
  when: not has_firewalld and has_iptables
